<?php

function egrin2_help($path, $arg) {
    switch ($path) {
    case "admin/help#egrin2":
        return t("Displays data from EGRIN2 APIs");
        break;
    }
}

function egrin2_block_info() {
    $blocks['egrin2'] = array('info' => t('EGRIN2'),
                              'cache' => DRUPAL_CACHE_PER_ROLE,);
    $blocks['corem_table'] = array('info' => t('EGRIN2 Corem Table'),
                                   'status' => TRUE,
                                   //'visibility' => BLOCK_VISIBILITY_LISTED,
                                   //'pages' => 'node/*',
                                   );
    return $blocks;
}

function egrin2_block_view($delta='') {
    switch ($delta) {
    case 'egrin2':
        $block['subject'] = t('EGRIN2 Dummy');
        if (user_access('access content')) {
            $block['content'] = t('EGRIN2 content');
        }
        break;
    case 'corem_table':
        $block['subject'] = t('Corem Table');
        if (user_access('access content')) {
            $block['content'] = t('Corem table content');
        }
        break;
    }
    return $block;
}

/*
 * Configuration section for the plugin
 * The components in this plugin need to know the base URL of the EGRIN2 API.
 * It uses the Drupal form API to create a persistent value for this setting
 */
function egrin2_menu() {
    $items = array();
    $items['admin/config/content/egrin2'] = array('title' => 'EGRIN2',
                                                  'description' => 'Configuration for EGRIN2 module',
                                                  'page callback' => 'drupal_get_form',
                                                  'page arguments' => array('egrin2_form'),
                                                  'access arguments' => array('access administration pages'),
                                                  'type' => MENU_NORMAL_ITEM,
                                                  );
    return $items;
}

function egrin2_form($form, &$form_state) {
    $form['egrin2_url'] = array('#type' => 'textfield',
                                '#title' => t('EGRIN2 API URL'),
                                '#default_value' => variable_get('egrin2_url', ''),
                                '#size' => 100,
                                '#maxlength' => 100,
                                '#description' => t('The URL of the EGRIN2 web service API.'),
                                '#required' => TRUE,
                                );
    return system_settings_form($form);
}
